services:
  sirepo-jti_franken:
    container_name: sirepo-jti_franken
    image: image_sirepo-jti_franken
    restart: always
    build: 
      dockerfile: Dockerfile
      context: .
    ports: 
      - 8080:80
      - 444:443
      - 444:443/udp
    env_file: 
      - .env 
    # volumes:
    #   - .:/app #this copy all file and folder in this project to /app inside container path 
    #   - ./Caddyfile:/etc/caddy/Caddyfile #this copy caddy in this project to /etc/caddy/Caddyfile inside container path

  mysql_database:
    container_name: mysql_sirepo
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sirepojti_db
    ports:
      - "3308:3306"

  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin:latest
    ports:
      - "81:80"
    environment:
      PMA_ARBITARY: 1
      PMA_HOST : mysql_database
      PMA_PORT : 3306
