services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sirepojti_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: sirepojti_mysql_database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sirepojti_database       
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sirepojti_user_db         
      MYSQL_PASSWORD: userpassword  
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: sirepojti_nginx
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

volumes:
  dbdata:


networks:
  laravel:
    driver: bridge
