services:
  sirepo-jti_franken:
    container_name: sirepo-jti_franken
    image: image_sirepo-jti_franken
    restart: always
    build: 
      dockerfile: worker.frankenphp.dockerfile
      context: .
    ports: 
      - 8080:80
      - 444:443
      - 444:443/udp
    env_file: 
      - .env 
    volumes:
      - .:/app #this copy all file and folder in this project to /app inside container path or its mean this current folder connected to the /app inside docker container if there a change its impact to other
      - caddy_data:/data
      - caddy_config:/config

  mysql_database:
    container_name: mysql_sirepo
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sirepojti_db
    ports:
      - "3308:3306"

  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin:latest
    ports:
      - "81:80"
    environment:
      PMA_ARBITARY: 1
      PMA_HOST : mysql_database
      PMA_PORT : 3306

# Volumes needed for Caddy certificates and configuration
volumes:
  caddy_data:
  caddy_config:
