services:
  sirepo-jti_franken:
    container_name: sirepo-jti_franken
    image: image_sirepo-jti_franken
    build: .
    ports: 
      - 8001:80
      - 443:443
      - 443:443/udp
    env_file: 
      - .env 

  mysql_database:
    container_name: mysql_sirepo
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sirepojti_db
    ports:
      - "3308:3306"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - "81:80"
    environment:
      PMA_ARBITARY: 1
      PMA_HOST : mysql_database
      PMA_PORT : 3306
