name: Deploy Laravel Application to Production Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      # with dev library install
      - name: Install Composer Dependencies
        run: composer install --optimize-autoloader --no-progress --no-interaction --prefer-dist

      # no dev library install
      # - name: Install Composer Dependencies
      #   run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

      # - name: Install Node
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "20"

      # - name: Install NPM Dependencies
      #   run: npm install

      # - name: Build NPM Assets
      #   run: npm run build

      - name: Set Up Deployer
        run: curl -LO https://deployer.org/deployer.phar && mv deployer.phar bin/dep && sudo chmod +x bin/dep

      - name: Deploy to Production Server
        uses: deployphp/action@v1
        with:
          dep: deploy
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Run Remote/Artisan Commands
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.VPS_HOST }}
      #     username: ${{ secrets.VPS_USER }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd ${{ secrets.APP_PATH }}
      #       echo "Pulling from GitHub"
      #       git pull origin
      #       echo "Installing packages using composer"
      #       composer install
      #       echo "test"
      #       php artisan test
      #       echo "Migrating database"
      #       php artisan migrate --force
      #       echo "The app has been build and deploy"
